---
- name: Activity 1 Playbook
  hosts: webservers
  become: true
  tasks:

  - name: Install docker.io
    apt:
     force_apt_get: yes
     update_cache: yes
     name: docker.io
     state: present

  - name: Install pip3
    apt:
     force_apt_get: yes
     name: python3-pip
     state: present

  - name: Install Docker Python
    pip:
     name: docker
     state: present

  - name: Download and install
    docker_container:
     name: dvwa
     image: cyberxsecurity/dvwa
     state: started
     published_ports: 90:90

  - name: Enable docker
    systemd:
     name: docker
     enabled: yes